### ISSUE TITLE
Location button does not show that it is toggled

### ISSUE THREAD

**Issue by TokyoRose** [mariotaku/twidere#254] opened 2015-02-20 00:55 UTC
Regarding 0.3.0-dev-google. If the Location button has been pressed, it shows a notification that says 'location', but there is nothing in the UI that persists to remind the user that they are about to reveal their present location in the tweet. The button continues to appear as though it has not been toggled, even though it has been toggled.

There are situations where that is a security/privacy risk.

Can that button be made to change colour or in some way indicate that it has been toggled?

Also, can there be a way in Settings, to disable the location button so that it cannot be pressed at all?

**Comment by mkody** [comment] 2015-02-20 21:42
Looks like a duplicate of #246

> fixed in recent commits, thanks for reporting :D

**Comment by yamatt** [comment] 2015-03-31 09:43
#246 was for the previous release. This bug concerns 0.3.0. However when I click on the location button in 0.3.0 the little marker goes blue and coordinates are displayed. Huge improvement.

**Comment by mariotaku** [comment] 2015-03-31 10:22
OK, I'll close this issue.

**Closed by mariotaku** 2015-03-31 10:22 UTC
